# Belgian Temperature project with numpy

I will make a 3D array to store all the readings.
Not every station start at same year

In [1]:
import numpy as np
import os

## Store station name into array

In [2]:
working_dir = "/Users/uwev/PycharmProjects/data-science/data_files/belgian_temperature/"
files_arr = np.array([os.listdir(working_dir)], dtype=str).reshape(16)  #SHAPE IS (16,)
station_name_arr = np.empty((len(files_arr),), dtype='U30')             #SHAPE IS (16,)

for i, file in enumerate(files_arr):
    with open(os.path.join(working_dir,file), 'r') as fh:
        station_name_arr[i] = fh.readlines()[3].replace("# Series name : ", "").strip()

print(files_arr)
station_name_arr

['ho_monthly_series_203_tn_v2024_01.csv'
 'ho_monthly_series_220_tn_v2024_01.csv'
 'ho_monthly_series_212_tn_v2024_01.csv'
 'ho_monthly_series_221_tn_v2024_01.csv'
 'ho_monthly_series_213_tn_v2024_01.csv'
 'ho_monthly_series_223_tn_v2024_01.csv'
 'ho_monthly_series_208_tn_v2024_01.csv'
 'ho_monthly_series_216_tn_v2024_01.csv'
 'ho_monthly_series_219_tn_v2024_01.csv'
 'ho_monthly_series_224_tn_v2024_01.csv'
 'ho_monthly_series_217_tn_v2024_01.csv'
 'ho_monthly_series_201_tn_v2024_01.csv'
 'ho_monthly_series_218_tn_v2024_01.csv'
 'ho_monthly_series_222_tn_v2024_01.csv'
 'ho_monthly_series_206_tn_v2024_01.csv'
 'ho_monthly_series_210_tn_v2024_01.csv']


array(['BRUXELLES-ZAVENTEM', 'MAREDSOUS', 'OOSTENDE', 'GEMBLOUX',
       'SINT-TRUIDEN', 'THIMISTER', 'JALHAY', 'LEOPOLDSBURG', 'STAVELOT',
       'UCCLE', 'ROCHEFORT', 'DEURNE', 'CHIMAY', 'MONT-RIGI', 'EZEMAAL',
       'LEUVEN'], dtype='<U30')

## get year range

In [3]:
year_range_arr = np.array([], dtype=int)
for file in files_arr:
    df_year = np.genfromtxt(os.path.join(working_dir,file), delimiter=',', usecols=0, dtype=int, skip_header=9)
    year_range_arr = np.union1d(year_range_arr, df_year)

year_range_arr

array([1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890,
       1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901,
       1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912,
       1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923,
       1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934,
       1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945,
       1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956,
       1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967,
       1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978,
       1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989,
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023])

In [4]:
months = 12
df_arr = np.full(shape=(len(station_name_arr), len(year_range_arr)+1, months), fill_value=np.nan)
for station_idx, file in enumerate(files_arr):
    df = np.genfromtxt(os.path.join(working_dir,file), delimiter=',', skip_header=9)
    for row in df:
        temp = int(row[0])
        diff_temp = temp - np.min(year_range_arr)
        df_arr[station_idx, diff_temp] = row[1:13]
# chack for one station the last 5 rows & the firts 10 rows
print(df_arr[0,-6:-1,:]) # LAST VALUES CORRESPOND with "ho_monthly_series_203_tn_v2024_01.csv"
print(df_arr[0,0:10,:]) # start at 1889 so 9 NAN LINES

[[ 1.1  2.1  4.5  4.4  6.8 12.5 13.3 13.6 10.1  8.9  3.5  3.1]
 [ 2.9  3.8  2.4  5.   7.2 12.5 12.8 15.5 10.3  8.4  5.6  3.2]
 [ 0.9  0.9  2.4  1.6  6.6 13.  13.5 13.1 11.1  7.8  3.7  3. ]
 [ 2.2  3.3  2.3  4.4  9.5 12.1 12.8 14.6 10.9  9.9  6.1  1.3]
 [ 3.2  1.8  3.3  4.4  8.1 13.2 14.  14.  13.5 10.   5.7  5. ]]
[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [-2.4 -2.3 -0.4  3.6  9.5 11.6 11.3 11.3  8.4  5.7  2.2 -2.2]]


In [ ]:
print(df_arr[6,-5:-1,:]) #  "ho_monthly_series_208_tn_v2024_01.csv" 1880 - 2023 SO NO NAN VALLUES
print(df_arr[6,0:10,:])

[[ 1.8  3.2  2.1  4.6  6.1 12.6 12.1 15.9 10.   8.5  5.4  3.1]
 [ 0.2  1.3  1.5  1.1  6.6 13.7 13.7 12.6 11.   7.   2.8  2.7]
 [ 1.1  2.4  2.2  3.8  9.2 12.2 13.1 14.5 10.7  9.8  6.5  0.8]
 [ 2.2  1.9  3.   3.4  7.8 13.4 13.8 13.8 13.2  9.9  5.3  4.1]]
[[-5.9  1.5  0.9  4.8  5.2 10.4 12.4 12.2 10.9  4.9  1.8  3.3]
 [-6.9  0.2  1.8  2.4  6.8  8.9 13.3 12.3  9.6  3.1  6.2  0.5]
 [-0.9  0.7  3.3  3.5  7.7 10.7 12.3 12.3 10.2  7.7  3.6  1. ]
 [ 0.5  2.5 -3.   3.   7.3 10.6 12.9 12.  10.2  6.8  3.1 -0. ]
 [ 2.9  2.1  2.2  2.7  7.8  8.7 14.  13.9 11.   5.8  0.8  1.3]
 [-3.9  3.3 -0.7  4.8  6.3 11.3 11.8  9.4  9.2  5.5  1.1 -1.2]
 [-1.7 -4.8 -0.6  4.2  7.6 10.2 12.3 11.9 10.5  8.3  3.7 -0.7]
 [-3.5 -2.8 -3.2  1.9  6.1  9.9 12.4 10.3  8.5  3.3  1.9 -2.3]
 [-4.1 -5.8 -0.8  1.9  6.6 11.3 10.5 10.3  7.   4.   4.2  1.3]
 [-3.4 -4.9 -2.4  3.2  9.9 12.4 11.6 11.4  7.7  5.8  1.2 -3.1]]


In [9]:
#Store to NPY file so I can do calculations in other python file
with open("data_files/belgian_temp.npy", "wb") as fw:
    np.save(fw, df_arr)
    np.save(fw, year_range_arr)
    np.save(fw, station_name_arr)
    np.save(fw, files_arr)
